name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [sh, bash]
        include:
          - os: ubuntu-latest
            shell: dash
          - os: macos-latest
            shell: zsh
    steps:
      - uses: actions/checkout@v4
      - name: Run tests with ${{ matrix.shell }}
        env:
          SHELL_UNDER_TEST: ${{ matrix.shell }}
        run: |
          ${{ matrix.shell }} to_unix_time/test_to_unix_time.sh
          ${{ matrix.shell }} from_unix_time/test_from_unix_time.sh
