name: Test with multiple timezones

on:
  push:
  pull_request:

jobs:
  test-timezone:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        tz:
          - UTC
          - Asia/Tokyo
          - Asia/Kolkata
          - America/Phoenix
          - Pacific/Honolulu
        shell: [sh, bash, dash]
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests with ${{ matrix.shell }} in ${{ matrix.tz }}
        env:
          TZ: ${{ matrix.tz }}
          SHELL_UNDER_TEST: ${{ matrix.shell }}
        run: ${{ matrix.shell }} test.sh
      - name: Run property-based tests with ${{ matrix.shell }} in ${{ matrix.tz }}
        env:
          TZ: ${{ matrix.tz }}
          SHELL_UNDER_TEST: ${{ matrix.shell }}
        run: ${{ matrix.shell }} property_tests/property_test_unix_time.sh
